move mutex in watch_pool_routine to threads
TinkoffCreditSystems/stream-client pull request #8
Opened 2021-07-26 01:04 UTC by zodinyac

2021-07-29 07:44 UTC, suboch requested changes
Есть ошибки :(

2021-07-29 07:44 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        // release poll mutex after removing old sessions
опечатка poll

2021-07-29 07:44 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        pool_lk.unlock();
Ошибка. Как только ты отпустил pool_lk, то пул может измениться, значение vacant_places станет неверным, и ниже произойдёт какая-то дичь.

2021-07-29 07:44 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +                    pool.emplace_back(clock_type::now(), std::move(new_session));
А если нет, то что? Новая сессия просто выкинется в помойку?

2021-07-29 07:44 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        auto add_session = [&connector = this->connector_, &pool = this->sesson_pool_, &pool_mutex = this->pool_mutex_,
Выглядит так, что проще захватить this

2021-07-29 23:37 UTC, zodinyac commented on include/stream-client/connector/impl/connection_pool.ipp
> +                    pool.emplace_back(clock_type::now(), std::move(new_session));
А пусть сохраняется.

2021-07-30 07:34 UTC, suboch requested changes
две небольшие правки по существу, одна косметическая

2021-07-30 07:34 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +                std::unique_lock<std::timed_mutex> pool_lk(this->pool_mutex_);
Зачем ты заменил на `timed_mutex`, если не пользуешься никакими таймаутами с ним?

2021-07-30 07:34 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +                auto new_session = this->connector_.new_session();
Можно не добавлять везде `this->`, если захватил `this`

2021-07-30 07:34 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(50));
Раньше мы спали, только если не добавили никого, а теперь спим всегда. Не будет ли от этого хуже?
Кажется, логика должна стать такой:
```cpp
if (vacant_places == 0) {
  спать
}
```

2021-07-30 07:34 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        pool_lk.unlock();
обсудили в личке, что это нормально

2021-07-30 11:40 UTC, suboch requested changes
Ещё заметил пару мелочей. По поводу CPU spooling'а не передумал.

2021-07-30 11:40 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        // release pool mutex after removing old sessions
Можно даже ещё на шаг выше поднять, до вычисления переменной vacant_places, там же только локальные переменные и константы участвуют.

2021-07-30 11:40 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(50));
Я подумал, и всё-таки не нужно спать всегда.
Недаром тут явно написан коммент // stop cpu spooling if nothing has been added

Как ты знаешь, getting new session is time consuming operation, и пока мы их создавали и добавляли -- много воды могло утечь. В худшем случае, если сейчас быстро отстрелялись, то ничего страшного -- быстренько крутнём while вхолостую и на следующей итерации цикла поспим.

2021-07-30 11:40 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +        // creating new sessions may be slow and we want add them simultaneously;
creating new sessions may be slow, and we want TO add them simultaneously;

2021-07-30 11:40 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +                std::unique_lock<std::timed_mutex> pool_lk(pool_mutex_);
Я бы предложил заодно красиво сделать. Не надо unique_lock вручную анлочить, есть же RAII. Да и вообще достаточно более простого лока:
```cpp
{
    std::lock_guard<std::timed_mutex> lock(pool_mutex_);
    sesson_pool_.emplace_back(clock_type::now(), std::move(new_session));
}
```

2021-07-30 13:26 UTC, zodinyac commented on include/stream-client/connector/impl/connection_pool.ipp
> +                std::unique_lock<std::timed_mutex> pool_lk(pool_mutex_);
Что сделать `unlock()` до того, как мы сделаем `pool_cv_.notify_one()`.

2021-07-30 13:47 UTC, suboch approved these changes
done

2021-07-30 13:47 UTC, suboch commented on include/stream-client/connector/impl/connection_pool.ipp
> +                std::unique_lock<std::timed_mutex> pool_lk(pool_mutex_);
Я не убедил, что {}  красивее, чем .unlock()

2021-07-30 13:48 UTC, merged